logging:
  charset:
    console: utf-8
    file: utf-8
  config: classpath:log4j2-spring.xml
  exception-conversion-word: '%wEx'
  file:
    name: logs/${spring.application.name}.log
  level:
    #RACE,DEBUG,INFO,WARN,ERROR,FATAL,OFF
    root: ${ENV_LOGGING_LEVEL_ROOT:WARN}
  pattern:
    console: '%d{${logging.pattern.dateformat}} ${logging.pattern.level} %l %m%n${logging.exception-conversion-word}'
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    file: '%d{${logging.pattern.dateformat}} ${logging.pattern.level} %l %m%n${logging.exception-conversion-word}'
    level: '%5p'
  size:
    file: ${ENV_LOGGING_FILE_SIZE:5MB}
  threshold:
    console: TRACE
    file: TRACE
