medical:
    security:
        jwt-supoprt: true
        expiressSecond: 3600
        no-auth-urls:
            - /
            - /swagger-ui/index.html
            - /swagger-ui.html
            - /swagger-ui/**
            - /webjars/**
            - /v3/api-docs/**
            - /v3/api-docs
            # 新版 API
            - /novel/book/**
            - /novel/chapter/**
            - /novel/author/**
            # 管理后台 API (统一前缀)
            - /api/**
            - /users/**
            - /file/**
            # 静态资源
            - /upload/**
            # 前台 API
            - /xiaoshuoxinxi/**
            - /xiaoshuoleixing/**
            - /config/**
            - /messages/**
            - /yonghu/**
            - /zuozhe/**
            - /news/**
            - /storeup/**
            - /discussxiaoshuoxinxi/**
            - /chapterxiaoshuoxinxi/**
            # 选项接口
            - /option/**
        user:
            username: admin
            password: admin
            full-name: 系统管理员
